# Generated by Django 3.2.5 on 2021-11-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendorproduct',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='VendorProduct',
        ),
    ]
