# Generated by Django 3.2.5 on 2021-11-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_product_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_before_discount',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
