# Generated by Django 3.2.5 on 2021-11-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
