# Generated by Django 3.2.5 on 2021-11-28 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0011_alter_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
