# Generated by Django 3.2.5 on 2021-11-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('product_title', models.TextField()),
                ('product_price', models.TextField()),
                ('price_before_discount', models.IntegerField()),
            ],
        ),
    ]
